schema_version = "1.0.0"

id = "nmanager"
version = "0.6.4"
name = "NManager"
tagline = "Rename, reorder, hide and group N-panel tabs"
maintainer = "Jordan Moss"
type = "add-on"

blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]
